### PR TITLE
Add battery charge/discharge stats

### PR DESCRIPTION
**Pull request by danieltwagner**
Thanks a bunch for creating this library!
I noticed battery state was missing; this patch adds support for charge/discharge counters

### CODE REVIEW

**Comment by wopfel** [comment]
Hi, 
Thanks for your patch. Sounds really interesting since I'm also interested in my battery counters. 

I've applied your patch to my local repository. When running `sunnyportal2file` the output doesn't change, meaning there are still only min_power, mean_power, and max_power in the output file (json, in my case). Should it print the battery counters in the output file too?

I'm really new into this script. So please excuse if asking dumb questions 😊 

Kind regards,
Bernd

**Comment by joebe975** [comment]
@wopfel: You could start by looking at [get_data_for_period](https://github.com/erijo/sunnyportal-py/blob/600f57d8539539aa4aa3a275c343d53d3baa569b/bin/sunnyportal2file#L295) and [DataFrameSaver](https://github.com/erijo/sunnyportal-py/blob/600f57d8539539aa4aa3a275c343d53d3baa569b/bin/sunnyportal2file#L49) if you want to add the support.

**Comment by danieltwagner** [comment]
As @joebe975 has pointed out, this patch only modifies the underlying library. As I don't use any of the binaries I did not modify those.

**Comment by erijo** [comment]
Thanks @danieltwagner!

**Pull request merged**
